### ISSUE TITLE
测试数据

### ISSUE THREAD

**Issue by or0or1** [jzfai/vue3-admin-plus#10]
请问一下：  

       1，测试数据是在哪里隐藏的？ 
       2， 如何实现向让匿名用户不用登录也可以访问指定的页面？  登录成功后会执行什么操作？ 写cookie？ 
            看vue2的版本，很明显看到有：
```
      const data = response.data
      Cookies.set('Token', response.data.token) //登录成功后将token存储在cookie之中
      commit('SET_TOKEN', data.token)
```   

       但vue3的版本看不懂。 求指教。 

       

谢谢

真香！

**Comment by jzfai** [comment]
1.测试数据：请求的是真实的服务器数据，没用mock
2.token保存改为用localstroage移除了Cookies, 不需要登录也能访问，可以设置setting文件里的isNeedLogin为false不需要登录可以直接进入

**Comment by or0or1** [comment]
谢谢ls。但找了一圈，没找到在哪里配置了服务器地址。
