### ISSUE TITLE
资源打包

### ISSUE THREAD

**Issue by xumqfaith** [jzfai/vue3-admin-plus#11]
`build: {
      assetsDir:'static/img',
      rollupOptions:{
        output:{
          chunkFileNames:'static/js/[name]-[hash].js',
          entryFileNames:'static/js/[name]-[hash].js',
          assetFileNames:'static/[ext]/[name]-[hash].[ext]',
        }
      }
    },`

建议优化build，这样img、css、js就在不同的文件夹了

**Comment by jzfai** [comment]
我觉的你的建议挺好的，你pull一下，我把你的代码合并下
