### ISSUE TITLE
tagsView组件 刷新报错

### ISSUE THREAD

**Issue by Ych0524** [jzfai/vue3-admin-plus#16]
![image](https://user-images.githubusercontent.com/63226619/145502735-e1b3dde3-b540-476b-a598-5e996158f7fd.png)

**Comment by jzfai** [comment]
能提供下具体的步骤吗

**Comment by Ych0524** [comment]
> 能提供下具体的步骤吗
![image](https://user-images.githubusercontent.com/63226619/145504241-21e8ae5a-f684-459c-8fe3-9039e843c7fc.png)

**Comment by jzfai** [comment]
这边将会在下个版本修复
