### ISSUE TITLE
是否会跟进技术栈更新

### ISSUE THREAD

**Issue by Corgis** [jzfai/vue3-admin-plus#21]
感觉是vue3 + element-plus完全复刻了vue-element-admin 很香，感谢作者！！

以下建议为个人想法，谢谢。
vuex个人感觉可以更新到pinia
添加 unplugin-auto-import 自动引入插件

**Comment by jzfai** [comment]
根据我的个人经验，由于Pinea是轻量级的，体积很小，它适合于中小型应用。它也适用于低复杂度的Vue.js项目，因为一些调试功能，如时间旅行和编辑仍然不被支持。

将 Vuex 用于中小型 Vue.js 项目是过度的，因为它重量级的，对性能降低有很大影响。因此，Vuex 适用于大规模、高复杂度的 Vue.js 项目。
但是：vuex毕竟是官方的东西，更加可靠，目前没有考虑把vuex换成pinia。
如果你需要pinia可以集成下，集成后可以pull推送到本架构，我可以集成到pinia分支
