### ISSUE TITLE
关于 获取git hash值 未捕获异常的问题

### ISSUE THREAD

**Issue by Corgis** [jzfai/vue3-admin-plus#25]
当clone代码后，不是git空间或无提交记录时，跑项目 会提示报错
![image](https://user-images.githubusercontent.com/13865529/149305769-36cdfc0c-9ec9-4685-9600-e482d5a1b17e.png)

我这边尝试修改了捕获异常，需要我提交么？还是你直接修改掉。

**Comment by jzfai** [comment]
可以的，之前没考考虑到上述情况，你pull下，我合并下

**Comment by Corgis** [comment]
> 可以的，之前没考考虑到上述情况，你pull下，我合并下

这边没有远端推送权限

**Comment by jzfai** [comment]
你fork 然后 推送大fork 上 在pull
