### ISSUE TITLE
请教下为啥移除了@vue/compiler-sfc？

### ISSUE THREAD

**Issue by xysaifeng** [jzfai/vue3-admin-plus#28]
我的理解是v3搭配使用@vue/compiler-sfc，就像v2中使用vue-template-compiler

**Comment by jzfai** [comment]
https://www.npmjs.com/package/@vue/compiler-sfc
Note: as of 3.2.13+, this package is included as a dependency of the main vue package and can be accessed as vue/compiler-sfc. This means you no longer need to explicitly install this package and ensure its version match that of vue's. Just use the main vue/compiler-sfc deep import instead.
