### ISSUE TITLE
ts 是主流，为什么不一步到位呢？

### ISSUE THREAD

**Issue by GreatAuk** [jzfai/vue3-admin-plus#31]

**Comment by jzfai** [comment]
为了照顾不会ts的同学

**Comment by ponychoker** [comment]
你好同学，是有ts版本的 https://github.com/jzfai/vue3-admin-ts

**Comment by pecopeco** [comment]
还是有很多第三方npm包不支持ts，看需求吧

**Comment by Dongary** [comment]
我就不喜欢用ts，是真不喜欢

**Comment by Haiwar** [comment]
![Uploading image.png…]()

**Comment by Haiwar** [comment]
![image](https://user-images.githubusercontent.com/35055270/202989042-ecb32016-8086-43e6-a345-c12a59367e7b.png)
