### ISSUE TITLE
希望能增加对接后端的一些教程

### ISSUE THREAD

**Issue by heiheiheiheiheihei** [jzfai/vue3-admin-plus#34]
看了axiosReq.js，mockAxiosReq.js，vite.config.js，一头雾水，求大佬指点

**Comment by heiheiheiheiheihei** [comment]
mock/example.js，src/views/example/mock-test/MockTest.vue感觉是从这里入手

**Comment by jzfai** [comment]
可以看下axiosReq 请求篇https://juejin.cn/post/7042515597992656909
