### ISSUE TITLE
横板菜单警告问题

### ISSUE THREAD

**Issue by Corgis** [jzfai/vue3-admin-plus#40]
菜单设置成横板会出现以下错误提示
![image](https://user-images.githubusercontent.com/13865529/156280274-1cb1936d-3c13-47c8-821e-6f532a380cb5.png)
测试了下，直接用官方的横板菜单例子，缩小屏幕是不会出现这个提示的

**Comment by Corgis** [comment]
![image](https://user-images.githubusercontent.com/13865529/156310470-ce4cb453-2f68-4df1-bba8-bbb45d0c088b.png)
看了下 是这个template的问题，改为标签节点就ok了

**Comment by ponychoker** [comment]
感谢反馈，后续版本会修复此问题

**Comment by jzfai** [comment]
@Corgis @ponychoker 可以提交下 pull， 我合并fix下

**Comment by jzfai** [comment]
fix it in v1.4.3
