### ISSUE TITLE
本地运行的时候正常，打包之后却显示变量未定义

### ISSUE THREAD

**Issue by hjldev** [jzfai/vue3-admin-plus#6]
使用yarn run dev时正常，打包后proxy.name引用变量提示变量未定义，我打印出来proxy的内容，发现并没有我预先定义的name

**Comment by jzfai** [comment]
请尽量不要用proxy进行定义变量，script-setup中 定义的变量默认在本组件使用，不会暴露到实例上，如果需要暴露到实例上需要使用defineExpose({ helloFunc });进行暴露
