### ISSUE TITLE
在线demo，请求发生错误

### ISSUE THREAD

**Issue by Eplayed** [jzfai/vue3-admin-plus#62]
let dataBaseUrl = $ref(
  'https://github.jzfai.top/micro-service-api/basis-func/dataBase/getAllDatabaseOrTable/micro-service-plus'
)
请求发生错误，可以修复下在线demo吗

{
    "msg": "Could not open JDBC Connection for transaction; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
    "flag": false,
    "code": 20001
}

**Comment by jzfai** [comment]
已fix
