### ISSUE TITLE
关于tagsView的讨论 可能算功能范围或者bug

### ISSUE THREAD

**Issue by Corgis** [jzfai/vue3-admin-plus#65]
以 首页 和 低代码平台 两个菜单为例
进入项目地址 此时tagview上有 一个名为  首页 的tag
第一步：点击低代码菜单  则多了一个名为 低代码平台的tag
第二步：通过点击tagview回到 首页
第三步：在首页写一个按钮  功能为 路由跳转 到 低代码平台页   push( { name:'xxx’, query: { name = "test" } } ) 
              此时跳转到低代码页后 url上 会 带上 ?name=test  https://github.jzfai.top/vue3-admin-plus/#/codeGenerator/index?name=test
第四步：通过点击tagview 跳回首页 再 点击 tagview跳到 低代码平台页 url上的 name参数 未保留 消失了

简而言之  通过push 带上 query参数跳转的页面  切换其他页面 再通过tagview进入  query参数会消失
当然这可以归为 功能实现 而不是bug

不过 vue-element-admin  是 有能够保留的 该参数的

**Comment by jzfai** [comment]
感谢你的反馈这边会进行，issue的处理
