### ISSUE TITLE
运行 pnmp run dev 报错

### ISSUE THREAD

**Issue by kth8384** [jzfai/vue3-admin-plus#69]
运行 pnmp run dev 报错
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined

**Comment by kth8384** [comment]
node和npm版本："node":"v18.9.0","pnpm":"7.12.2"

**Comment by jzfai** [comment]
node版本建议使用16+ 小于18
