### ISSUE TITLE
Button group has margin left

### ISSUE THREAD

**Issue by munkeywolf00** [jzfai/vue3-admin-plus#74]
If multiple button inside button-group, non first child has margin left.
This is in base and china-red theme. Not sure in other theme.

My initial fix:
.el-button-group > .el-button + .el-button {
  margin-left: 0;
}

![button-group](https://user-images.githubusercontent.com/119492966/219663489-fa0a8600-1124-40c3-baf7-e93611f7c689.JPG)

**Comment by jzfai** [comment]
thanks for you advise,   i find the issue in   

//src/theme/base/element-plus/button.scss

  .el-button + .el-button {
    margin-left: 12px;
  }

you can  notes it  and fix the issue

i will  fix it  in next version
