### ISSUE TITLE
showTagsView not cleared when false

### ISSUE THREAD

**Issue by munkeywolf00** [jzfai/vue3-admin-plus#75]
When showTagsView is false, height is not updated to where there should not be --tag-view-height. So it creates a "footer like"  view below. I fixed this in my local and I forgot how I did it.

This case also happens during scroll in src/styles/index.scss.

![dashboard-no-tags-views](https://user-images.githubusercontent.com/119492966/220143581-7c7d0913-fedb-4709-af5b-c54ea4c1bb40.JPG)

![dashboard-no-tags-views-inspect](https://user-images.githubusercontent.com/119492966/220143659-32b14ed7-98ff-4a4d-8fcc-e0555d2305e0.JPG)

**Comment by jzfai** [comment]
thanks for you advise 

you can send the  pr  to fix it

**Comment by munkeywolf00** [comment]
Sure. I will replicate it in new test and make a PR

**Comment by munkeywolf00** [comment]
@jzfai 
Here is my PR:
https://github.com/jzfai/vue3-admin-plus/pull/79
