### ISSUE TITLE
screenlock not working on tables

### ISSUE THREAD

**Issue by munkeywolf00** [jzfai/vue3-admin-plus#76]
Screenlock feature seems to not work correctly when background page has table.
But this doesn't seem to be an issue with VXE table like in demo site. 
I have no fix for this at the moment.

I am not sure if this is only in screenlocks.

EDIT:
It also shows checkboxes while in screenlock. 

![screenlock](https://user-images.githubusercontent.com/119492966/228790266-06235c52-7f8d-43d4-8183-2f2cb1be2ec2.JPG)

**Comment by ll-zhongyuan** [comment]
#77 Provides a solution to the problem you raised，There are no exceptions to the test environment

**Comment by munkeywolf00** [comment]
The solution seems to work. Thanks.
