### ISSUE TITLE
There is an issue with icon display when the sidebar is closed

### ISSUE THREAD

**Issue by MiaoLiMing** [jzfai/vue3-admin-plus#78]
![image](https://user-images.githubusercontent.com/47595856/228996801-cda715b6-a91b-4e91-9b32-c1c83d41766f.png)

**Comment by munkeywolf00** [comment]
The issue seems to be on .el-sub-menu__title having: 
padding-right: calc(var(--el-menu-base-level-padding) + var(--el-menu-icon-width));

Let's see what they find.

**Comment by jzfai** [comment]
icon logo  not exit , i will fix  it in next versionn
