### ISSUE TITLE
本地运行后打开网址报错

### ISSUE THREAD

**Issue by Lu-Rio** [jzfai/vue3-admin-plus#85]
运行后打开localhost:5005报错：AxiosError:Network Error

**Comment by Lu-Rio** [comment]
安装完axios后就报错了

**Comment by YYChildren** [comment]
具体的错误是：远端服务器在处理OPTIONS请求的时候，没有 返回 200 ok。只能请作者修复 `https://github.jzfai.top/micro-service-api`

Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by jzfai** [comment]
wait me fix it

**Comment by Lu-Rio** [comment]
It's ok

**Comment by jzfai** [comment]
fix it
